### PR TITLE
control fixes for existing controls

### LINKED ISSUE #6: Incorrect if statement to check if not a domain controller
The if condition used below does the work as intended 

https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/de9ec3f2fda31332b7b4290c31cc192175dcfb09/controls/V-73381.rb#L65

please correct to either of the following 
```
if !domain_role.eql?('4') && !domain_role.eql?('5')
```
```
if !(domain_role == '4') && !(domain_role == '5')
```

Corrections required on the following controls:

```
V-73377.rb:
  141    end
  142  
  143:   if !domain_role == '4' && !domain_role == '5'
  144      impact 0.0
  145      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73379.rb:
   72    end
   73  
   74:   if !domain_role == '4' && !domain_role == '5'
   75      impact 0.0
   76      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73381.rb:
   63    end
   64  
   65:   if !domain_role == '4' && !domain_role == '5'
   66      impact 0.0
   67      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73383.rb:
   51    end
   52  
   53:   if !domain_role == '4' && !domain_role == '5'
   54      impact 0.0
   55      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73385.rb:
   78    end
   79  
   80:   if !domain_role == '4' && !domain_role == '5'
   81      impact 0.0
   82      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73387.rb:
  108    end
  109  
  110:   if !domain_role == '4' && !domain_role == '5'
  111      impact 0.0
  112      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73389.rb:
  145    end
  146  
  147:   if !domain_role == '4' && !domain_role == '5'
  148      impact 0.0
  149      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73391.rb:
  156    end
  157  
  158:   if !domain_role == '4' && !domain_role == '5'
  159      impact 0.0
  160      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73393.rb:
  130    end
  131  
  132:   if !domain_role == '4' && !domain_role == '5'
  133      impact 0.0
  134      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73397.rb:
  131      end
  132    end
  133:   if !domain_role == '4' && !domain_role == '5'
  134      impact 0.0
  135      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73437.rb:
   65    end
   66  
   67:   if !domain_role == '4' && !domain_role == '5'
   68      impact 0.0
   69      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73439.rb:
   65    end
   66  
   67:   if !domain_role == '4' && !domain_role == '5'
   68      impact 0.0
   69      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73441.rb:
   65    end
   66  
   67:   if !domain_role == '4' && !domain_role == '5'
   68      impact 0.0
   69      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73495.rb:
   47    \\Windows\\PolicyDefinitions\\en-US directories respectively."
   48    domain_role = command('wmic computersystem get domainrole | Findstr /v DomainRole').stdout.strip
   49:   if !domain_role == '4' && !domain_role == '5'
   50      describe registry_key('HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System') do
   51        it { should have_property 'LocalAccountTokenFilterPolicy' }

V-73533.rb:
   31    domain_role = command('wmic computersystem get domainrole | Findstr /v DomainRole').stdout.strip
   32  
   33:   if !domain_role == '4' && !domain_role == '5'
   34      describe registry_key('HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows\\System') do
   35        it { should have_property 'EnumerateLocalUsers' }

V-73541.rb:
   32    domain_role = command('wmic computersystem get domainrole | Findstr /v DomainRole').stdout.strip
   33  
   34:   if !domain_role == '4' && !domain_role == '5'
   35      describe registry_key('HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Rpc') do
   36        it { should have_property 'RestrictRemoteClients' }

V-73611.rb:
   47    end
   48  
   49:   if !domain_role == '4' && !domain_role == '5'
   50      impact 0.0
   51      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73613.rb:
   71    end
   72  
   73:   if !domain_role == '4' && !domain_role == '5'
   74      impact 0.0
   75      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73615.rb:
   56    end
   57  
   58:   if !domain_role == '4' && !domain_role == '5'
   59      impact 0.0
   60      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73617.rb:
   78    end
   79  
   80:   if !domain_role == '4' && !domain_role == '5'
   81      impact 0.0
   82      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73629.rb:
   46    end
   47  
   48:   if !domain_role == '4' && !domain_role == '5'
   49      impact 0.0
   50      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73631.rb:
   38    end
   39  
   40:   if !domain_role == '4' && !domain_role == '5'
   41      impact 0.0
   42      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73651.rb:
   35    Controller is not available) to 4 logons or less."
   36    domain_role = command('wmic computersystem get domainrole | Findstr /v DomainRole').stdout.strip
   37:   if !domain_role == '4' && !domain_role == '5'
   38      describe registry_key('HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon') do
   39        it { should have_property 'CachedLogonsCount' }

V-73677.rb:
   44    for the policy to be enforced."
   45    domain_role = command('wmic computersystem get domainrole | Findstr /v DomainRole').stdout.strip
   46:   if !domain_role == '4' && !domain_role == '5'
   47      describe registry_key('HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Lsa') do
   48        it { should have_property 'RestrictRemoteSAM' }

V-73731.rb:
   65    end
   66  
   67:   if !domain_role == '4' && !domain_role == '5'
   68      impact 0.0
   69      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73733.rb:
   60    the Authenticated Users group."
   61    domain_role = command('wmic computersystem get domainrole | Findstr /v DomainRole').stdout.strip
   62:   if !domain_role == '4' && !domain_role == '5'
   63      describe.one do
   64        describe security_policy do

V-73737.rb:
   49    end
   50  
   51:   if !domain_role == '4' && !domain_role == '5'
   52      impact 0.0
   53      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73741.rb:
   48    end
   49  
   50:   if !domain_role == '4' && !domain_role == '5'
   51      impact 0.0
   52      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73757.rb:
   52    end
   53  
   54:   if !domain_role == '4' && !domain_role == '5'
   55      impact 0.0
   56      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73759.rb:
   83    is_domain = command('wmic computersystem get domain | FINDSTR /V Domain').stdout.strip
   84  
   85:   if !domain_role == '4' && !domain_role == '5'
   86      if is_domain == 'WORKGROUP'
   87        describe.one do

V-73761.rb:
   50    end
   51  
   52:   if !domain_role == '4' && !domain_role == '5'
   53      impact 0.0
   54      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73763.rb:
   57    is_domain = command('wmic computersystem get domain | FINDSTR /V Domain').stdout.strip
   58  
   59:   if !domain_role == '4' && !domain_role == '5'
   60      if is_domain == 'WORKGROUP'
   61        describe.one do

V-73765.rb:
   43    end
   44  
   45:   if !domain_role == '4' && !domain_role == '5'
   46      impact 0.0
   47      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73767.rb:
   53    is_domain = command('wmic computersystem get domain | FINDSTR /V Domain').stdout.strip
   54    domain_role = command('wmic computersystem get domainrole | Findstr /v DomainRole').stdout.strip
   55:   if !domain_role == '4' && !domain_role == '5'
   56      if is_domain == 'WORKGROUP'
   57        describe security_policy do

V-73769.rb:
   51    end
   52  
   53:   if !domain_role == '4' && !domain_role == '5'
   54      impact 0.0
   55      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73771.rb:
   65    is_domain = command('wmic computersystem get domain | FINDSTR /V Domain').stdout.strip
   66  
   67:   if !domain_role == '4' && !domain_role == '5'
   68      if is_domain == 'WORKGROUP'
   69        describe.one do

V-73773.rb:
   52    end
   53  
   54:   if !domain_role == '4' && !domain_role == '5'
   55      impact 0.0
   56      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73775.rb:
   77    is_domain = command('wmic computersystem get domain | FINDSTR /V Domain').stdout.strip
   78  
   79:   if !domain_role == '4' && !domain_role == '5'
   80      if is_domain == 'WORKGROUP'
   81        describe.one do

V-73777.rb:
   53    end
   54  
   55:   if !domain_role == '4' && !domain_role == '5'
   56      impact 0.0
   57      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'

V-73779.rb:
   36    domain_role = command('wmic computersystem get domainrole | Findstr /v DomainRole').stdout.strip
   37  
   38:   if !domain_role == '4' && !domain_role == '5'
   39      describe security_policy do
   40        its('SeEnableDelegationPrivilege') { should eq [] }

V-73395.rb:
  139    end
  140  
  141:   if !domain_role == '4' && domain_role == '5'
  142      impact 0.0
  143      desc 'This system is not a domain controller, therefore this control is not applicable as it only applies to domain controllers'
```

### LINKED ISSUE #7: Incorrect NIST Tag
Please remove the following lines from control V-73219 and V-73313.
It incorrectly overwrites a valid NIST tag specification above it.

https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/42fbf823bfe09d727a12476deda3762fe266e3f3/controls/V-73219.rb#L22

https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/0e48ee079b14b2799c22d28c2e40f986f3fdab4b/controls/V-73313.rb#L19

### LINKED ISSUE #8: Incorrect condition for Non applicable case
Please update the following Non applicable case condition 

https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/42fbf823bfe09d727a12476deda3762fe266e3f3/controls/V-73283.rb#L66

to 

```
if !temp_account.empty? 
```

### LINKED ISSUE #9: Fixes needed for control V-73259
* Current code wrongly assumes that control is NA for non Domain Controllers, however check text specifies it applicable to both

* Current code relies on parsing based on character positions which can be very brittle.

Please below powershell code that can return data in a JSON format which can be tested in describe blocks

for Domain Controllers:
```
json(command: " Search-ADAccount -AccountInactive -UsersOnly -TimeSpan 35.00:00:00 | ConvertTo-Json").params
```

For memeber servers:

```
user_query = <<-FOO
$users = @() 
  ([ADSI]('WinNT://{0}' -f $env:COMPUTERNAME)).Children | Where {
  $_.SchemaClassName -eq 'user' } | ForEach {
   $user = ([ADSI]$_.Path)
   $lastLogin = $user.Properties.LastLogin.Value


   $enabled = ($user.Properties.UserFlags.Value -band 0x2) -ne 0x2
   if ($lastLogin -eq $null) {
   $lastLogin = 'Never'
   }
   else {
   $today = Get-Date
   $diff = New-TimeSpan -Start "$lastLogin" -End $today
   $lastLogin = $diff.Days
   }

  $users += (@{ user = $user.Name.Value; lastLogin = $lastLogin; enabled = $enabled})
  }

$users | ConvertTo-Json
FOO

json(command: user_query).params
```

### LINKED ISSUE #11: Incorrect verbiage for domain_role check V-73221
https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/8b5935dafb445e7f0d5eab6f898cee57ea6356fa/controls/V-73221.rb#L89-L95

The please update the verbiage to the effect of
```
This applies to member servers and standalone systems. A
  separate version applies to domain controllers.

```

### LINKED ISSUE #12: Additional code needed for Domain controllers 'V-73283'
The control does not address, specific check for domain controllers.

https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/e6e7ff348bc5e5ed205ae51595aaf703d9459af2/controls/V-73283.rb#L39

### LINKED ISSUE #13: Test code V-73387 does not correctly test the target
Proposed fix:

```
text = command("dsquery * \"cn=Default Query Policy,cn=Query-Policies,cn=Directory Service, cn=Windows NT,cn=Services,cn=Configuration,dc=vspheread,dc=net\" -attr LDAPAdminLimits").stdout.

parse_config(text.gsub(/;/, "\n"),options).params
=> {"LDAPAdminLimits"=>"",
 "MaxValRange"=>"1500",
 "MaxReceiveBuffer"=>"10485760",
 "MaxDatagramRecv"=>"4096",
 "MaxPoolThreads"=>"4",
 "MaxResultSetSize"=>"262144",
 "MaxTempTableSize"=>"10000",
 "MaxQueryDuration"=>"120",
 "MaxPageSize"=>"1000",
 "MaxNotificationPerConn"=>"5",
 "MaxActiveQueries"=>"20",
 "MaxConnIdleTime"=>"900",
 "InitRecvTimeout"=>"120",
 "MaxConnections"=>"5000"}
```

### LINKED ISSUE #14: V-73391 are meant to validate audit definitions.
V-73391 is meant to validate audit definitions...currently it performs ACL checks

Similar affected controls
V-73389 V-73393 V-73397 V-73395

Similar affected controls but not currently part of PR#5
V-73399 

Suggest test code below:

```
$dn = (Get-ADDomain).DistinguishedName
(Get-ACL -Audit -Path AD:\$dn).Audit | ConvertTo-Json
[
    {
        "ActiveDirectoryRights":  983551,
        "InheritanceType":  1,
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  0,
        "AuditFlags":  3,
        "IdentityReference":  {
                                  "Value":  "Everyone"
                              },
        "IsInherited":  false,
        "InheritanceFlags":  1,
        "PropagationFlags":  0
    },
    {
        "ActiveDirectoryRights":  786464,
        "InheritanceType":  0,
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  0,
        "AuditFlags":  1,
        "IdentityReference":  {
                                  "Value":  "Everyone"
                              },
        "IsInherited":  false,
        "InheritanceFlags":  0,
        "PropagationFlags":  0
    },
    {
        "ActiveDirectoryRights":  256,
        "InheritanceType":  0,
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  0,
        "AuditFlags":  1,
        "IdentityReference":  {
                                  "Value":  "BUILTIN\\Administrators"
                              },
        "IsInherited":  false,
        "InheritanceFlags":  0,
        "PropagationFlags":  0
    },
    {
        "ActiveDirectoryRights":  256,
        "InheritanceType":  0,
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  0,
        "AuditFlags":  1,
        "IdentityReference":  {
                                  "Value":  "VSPHEREAD\\Domain Users"
                              },
        "IsInherited":  false,
        "InheritanceFlags":  0,
        "PropagationFlags":  0
    },
    {
        "ActiveDirectoryRights":  32,
        "InheritanceType":  1,
        "ObjectType":  "f30e3bbf-9ff0-11d1-b603-0000f80367c1",
        "InheritedObjectType":  "bf967aa5-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  3,
        "AuditFlags":  1,
        "IdentityReference":  {
                                  "Value":  "Everyone"
                              },
        "IsInherited":  false,
        "InheritanceFlags":  1,
        "PropagationFlags":  0
    },
    {
        "ActiveDirectoryRights":  32,
        "InheritanceType":  1,
        "ObjectType":  "f30e3bbe-9ff0-11d1-b603-0000f80367c1",
        "InheritedObjectType":  "bf967aa5-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  3,
        "AuditFlags":  1,
        "IdentityReference":  {
                                  "Value":  "Everyone"
                              },
        "IsInherited":  false,
        "InheritanceFlags":  1,
        "PropagationFlags":  0
    }
]
```

To see the meaning of numeric flags such as AuditFlags please try command below

```
PS C:\Users\Administrator> (Get-ACL -Audit -Path AD:\$dn).Audit 


ActiveDirectoryRights : GenericAll
InheritanceType       : All
ObjectType            : 00000000-0000-0000-0000-000000000000
InheritedObjectType   : 00000000-0000-0000-0000-000000000000
ObjectFlags           : None
AuditFlags            : Success, Failure
IdentityReference     : Everyone
IsInherited           : False
InheritanceFlags      : ContainerInherit
PropagationFlags      : None

ActiveDirectoryRights : WriteProperty, WriteDacl, WriteOwner
InheritanceType       : None
ObjectType            : 00000000-0000-0000-0000-000000000000
InheritedObjectType   : 00000000-0000-0000-0000-000000000000
ObjectFlags           : None
AuditFlags            : Success
IdentityReference     : Everyone
IsInherited           : False
InheritanceFlags      : None
PropagationFlags      : None

ActiveDirectoryRights : ExtendedRight
InheritanceType       : None
ObjectType            : 00000000-0000-0000-0000-000000000000
InheritedObjectType   : 00000000-0000-0000-0000-000000000000
ObjectFlags           : None
AuditFlags            : Success
IdentityReference     : BUILTIN\Administrators
IsInherited           : False
InheritanceFlags      : None
PropagationFlags      : None

ActiveDirectoryRights : ExtendedRight
InheritanceType       : None
ObjectType            : 00000000-0000-0000-0000-000000000000
InheritedObjectType   : 00000000-0000-0000-0000-000000000000
ObjectFlags           : None
AuditFlags            : Success
IdentityReference     : VSPHEREAD\Domain Users
IsInherited           : False
InheritanceFlags      : None
PropagationFlags      : None

ActiveDirectoryRights : WriteProperty
InheritanceType       : All
ObjectType            : f30e3bbf-9ff0-11d1-b603-0000f80367c1
InheritedObjectType   : bf967aa5-0de6-11d0-a285-00aa003049e2
ObjectFlags           : ObjectAceTypePresent, InheritedObjectAceTypePresent
AuditFlags            : Success
IdentityReference     : Everyone
IsInherited           : False
InheritanceFlags      : ContainerInherit
PropagationFlags      : None

ActiveDirectoryRights : WriteProperty
InheritanceType       : All
ObjectType            : f30e3bbe-9ff0-11d1-b603-0000f80367c1
InheritedObjectType   : bf967aa5-0de6-11d0-a285-00aa003049e2
ObjectFlags           : ObjectAceTypePresent, InheritedObjectAceTypePresent
AuditFlags            : Success
IdentityReference     : Everyone
IsInherited           : False
InheritanceFlags      : ContainerInherit
PropagationFlags      : None

```

### LINKED ISSUE #15: V-73377 current test code doesnt not actually test access.
V-73377 current test code doesnt not actually test access, it just looks for Allow flag but does not for what kind of access as specified in the check text

Proposed test:
```
$dn = (Get-ADDomain).DistinguishedName
PS C:\Users\Administrator> (Get-ACL -Path AD:\$dn).Access | ConvertTo-Csv | ConvertFrom-Csv | ConvertTo-Json
[
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "None",
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "None",
        "AccessControlType":  "Allow",
        "IdentityReference":  "Everyone",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "GenericRead",
        "InheritanceType":  "None",
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "None",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\ENTERPRISE DOMAIN CONTROLLERS",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "GenericRead",
        "InheritanceType":  "None",
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "None",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\Authenticated Users",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "GenericAll",
        "InheritanceType":  "None",
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "None",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\SYSTEM",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "CreateChild, Self, WriteProperty, ExtendedRight, Delete, GenericRead, WriteDacl, WriteOwner",
        "InheritanceType":  "All",
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "None",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Administrators",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty, ReadControl",
        "InheritanceType":  "None",
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "None",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ListChildren",
        "InheritanceType":  "All",
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "None",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "CreateChild, Self, WriteProperty, ExtendedRight, GenericRead, WriteDacl, WriteOwner",
        "InheritanceType":  "None",
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "None",
        "AccessControlType":  "Allow",
        "IdentityReference":  "VSPHEREAD\\Domain Admins",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "GenericAll",
        "InheritanceType":  "All",
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "None",
        "AccessControlType":  "Allow",
        "IdentityReference":  "VSPHEREAD\\Enterprise Admins",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "Self",
        "InheritanceType":  "Descendents",
        "ObjectType":  "9b026da6-0d3c-465c-8bee-5199d7165cba",
        "InheritedObjectType":  "bf967a86-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "CREATOR OWNER",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "1131f6ac-9c07-11d1-f79f-00c04fc2dcd2",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\ENTERPRISE DOMAIN CONTROLLERS",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "1131f6ab-9c07-11d1-f79f-00c04fc2dcd2",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\ENTERPRISE DOMAIN CONTROLLERS",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "1131f6aa-9c07-11d1-f79f-00c04fc2dcd2",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\ENTERPRISE DOMAIN CONTROLLERS",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "89e95b76-444d-4c62-991a-0facbeda640c",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\ENTERPRISE DOMAIN CONTROLLERS",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "b7c69e6d-2cc7-11d2-854e-00a0c983f608",
        "InheritedObjectType":  "bf967aba-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\ENTERPRISE DOMAIN CONTROLLERS",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "1131f6ae-9c07-11d1-f79f-00c04fc2dcd2",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\ENTERPRISE DOMAIN CONTROLLERS",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "b7c69e6d-2cc7-11d2-854e-00a0c983f608",
        "InheritedObjectType":  "bf967a9c-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\ENTERPRISE DOMAIN CONTROLLERS",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "b7c69e6d-2cc7-11d2-854e-00a0c983f608",
        "InheritedObjectType":  "bf967a86-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\ENTERPRISE DOMAIN CONTROLLERS",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "Self",
        "InheritanceType":  "Descendents",
        "ObjectType":  "9b026da6-0d3c-465c-8bee-5199d7165cba",
        "InheritedObjectType":  "bf967a86-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\SELF",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty, WriteProperty, ExtendedRight",
        "InheritanceType":  "Descendents",
        "ObjectType":  "91e647de-d96f-4b70-9557-d63ff4f3ccd8",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\SELF",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "WriteProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "ea1b7b93-5e48-46d5-bc6c-4df4fda78a35",
        "InheritedObjectType":  "bf967a86-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\SELF",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty, WriteProperty",
        "InheritanceType":  "All",
        "ObjectType":  "3f78c3e5-f79a-46bd-a0b8-9d18116ddc79",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\SELF",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit, ObjectInherit",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "05c74c5e-4deb-43b4-bd9f-86664c2a7fd5",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\Authenticated Users",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "ccc2dc7d-a6ad-4a7a-8846-c04e3cc53501",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\Authenticated Users",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "280f369c-67c7-438e-ae98-1d46f3c6f541",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\Authenticated Users",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "None",
        "ObjectType":  "b8119fd0-04f6-4762-ab7a-4986c76b3f9a",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "NT AUTHORITY\\Authenticated Users",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "1131f6ae-9c07-11d1-f79f-00c04fc2dcd2",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Administrators",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "1131f6ad-9c07-11d1-f79f-00c04fc2dcd2",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Administrators",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "1131f6ac-9c07-11d1-f79f-00c04fc2dcd2",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Administrators",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "1131f6ab-9c07-11d1-f79f-00c04fc2dcd2",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Administrators",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "1131f6aa-9c07-11d1-f79f-00c04fc2dcd2",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Administrators",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "89e95b76-444d-4c62-991a-0facbeda640c",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Administrators",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "GenericRead",
        "InheritanceType":  "Descendents",
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "bf967aba-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "GenericRead",
        "InheritanceType":  "Descendents",
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "bf967a9c-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "59ba2f42-79a2-11d0-9020-00c04fc2d3cf",
        "InheritedObjectType":  "bf967aba-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "GenericRead",
        "InheritanceType":  "Descendents",
        "ObjectType":  "00000000-0000-0000-0000-000000000000",
        "InheritedObjectType":  "4828cc14-1437-45bc-9b07-ad6f015e5f28",
        "ObjectFlags":  "InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "None",
        "ObjectType":  "b8119fd0-04f6-4762-ab7a-4986c76b3f9a",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "037088f8-0ae1-11d2-b422-00a0c968f939",
        "InheritedObjectType":  "4828cc14-1437-45bc-9b07-ad6f015e5f28",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "4c164200-20c0-11d0-a768-00aa006e0529",
        "InheritedObjectType":  "bf967aba-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "5f202010-79a5-11d0-9020-00c04fc2d4cf",
        "InheritedObjectType":  "4828cc14-1437-45bc-9b07-ad6f015e5f28",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "5f202010-79a5-11d0-9020-00c04fc2d4cf",
        "InheritedObjectType":  "bf967aba-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "None",
        "ObjectType":  "c7407360-20bf-11d0-a768-00aa006e0529",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "59ba2f42-79a2-11d0-9020-00c04fc2d3cf",
        "InheritedObjectType":  "4828cc14-1437-45bc-9b07-ad6f015e5f28",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "037088f8-0ae1-11d2-b422-00a0c968f939",
        "InheritedObjectType":  "bf967aba-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "bc0ac240-79a9-11d0-9020-00c04fc2d4cf",
        "InheritedObjectType":  "bf967aba-0de6-11d0-a285-00aa003049e2",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "bc0ac240-79a9-11d0-9020-00c04fc2d4cf",
        "InheritedObjectType":  "4828cc14-1437-45bc-9b07-ad6f015e5f28",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty",
        "InheritanceType":  "Descendents",
        "ObjectType":  "4c164200-20c0-11d0-a768-00aa006e0529",
        "InheritedObjectType":  "4828cc14-1437-45bc-9b07-ad6f015e5f28",
        "ObjectFlags":  "ObjectAceTypePresent, InheritedObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Pre-Windows 2000 Compatible Access",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "InheritOnly"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "e2a36dc9-ae17-47c3-b58b-be34c55ba633",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "BUILTIN\\Incoming Forest Trust Builders",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "1131f6aa-9c07-11d1-f79f-00c04fc2dcd2",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "VSPHEREAD\\Enterprise Read-only Domain Controllers",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "1131f6ad-9c07-11d1-f79f-00c04fc2dcd2",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "VSPHEREAD\\Domain Controllers",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ExtendedRight",
        "InheritanceType":  "None",
        "ObjectType":  "3e0f7e18-2c7a-4c10-ba82-4d926db99a3e",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "VSPHEREAD\\Cloneable Domain Controllers",
        "IsInherited":  "False",
        "InheritanceFlags":  "None",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty, WriteProperty",
        "InheritanceType":  "All",
        "ObjectType":  "5b47d60f-6090-40b2-9f37-2a4de88f3063",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "VSPHEREAD\\Key Admins",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "None"
    },
    {
        "ActiveDirectoryRights":  "ReadProperty, WriteProperty",
        "InheritanceType":  "All",
        "ObjectType":  "5b47d60f-6090-40b2-9f37-2a4de88f3063",
        "InheritedObjectType":  "00000000-0000-0000-0000-000000000000",
        "ObjectFlags":  "ObjectAceTypePresent",
        "AccessControlType":  "Allow",
        "IdentityReference":  "VSPHEREAD\\Enterprise Key Admins",
        "IsInherited":  "False",
        "InheritanceFlags":  "ContainerInherit",
        "PropagationFlags":  "None"
    }
]
```
ActiveDirectoryRights Cheatsheet
https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.activedirectoryrights?view=netframework-4.8

### LINKED ISSUE #16: Controls with multiple NIST Tags needs to be collapsed
Controls with multiple NIST Tags needs to be collapsed, otherwise only the last nist tag definition will be parsed.

```
tag "nist": ['IA-2', 'Rev_4']
tag "nist": ['IA-5 e', 'Rev_4']
```
should be modified to 
```
tag "nist": ['IA-2','IA-5 e','Rev_4']
```

Non compliant entries
```
Searching 275 files for "\s*tag "nist": .*$
\s*tag "nist": .*$
" (regex)

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73259.rb:
   13    tag "stig_id": 'WN16-00-000210'
   14    tag "fix_id": 'F-79703r1_fix'
   15:   tag "cci": ['CCI-000764', 'CCI-000795']
   16:   tag "nist": ['IA-2', 'Rev_4']
   17:   tag "nist": ['IA-5 e', 'Rev_4']
   18:   tag "documentable": false
   19    tag "check": "Open Windows PowerShell.
   20  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73273.rb:
   24    tag "stig_id": 'WN16-00-000280'
   25    tag "fix_id": 'F-79717r1_fix'
   26:   tag "cci": ['CCI-001199', 'CCI-002475', 'CCI-002476']
   27:   tag "nist": ['SC-28', 'Rev_4']
   28:   tag "nist": ['SC-28 (1)', 'Rev_4']
   29:   tag "documentable": false
   30    tag "check": "Verify systems that require additional protections due to
   31    factors such as inadequate physical protection or sensitivity of the data

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73279.rb:
    9    tag "stig_id": 'WN16-00-000310'
   10    tag "fix_id": 'F-79723r1_fix'
   11:   tag "cci": ['CCI-000366', 'CCI-002080']
   12:   tag "nist": ['CM-6 b', 'Rev_4']
   13:   tag "nist": ['CA-3 (5)', 'Rev_4']
   14:   tag "documentable": false
   15    tag "check": "Determine if a host-based firewall is installed and enabled on
   16    the system.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73359.rb:
   14    tag "stig_id": 'WN16-DC-000020'
   15    tag "fix_id": 'F-79801r1_fix'
   16:   tag "cci": ['CCI-001941', 'CCI-001942']
   17:   tag "nist": ['IA-2 (8)', 'Rev_4']
   18:   tag "nist": ['IA-2 (9)', 'Rev_4']
   19:   tag "documentable": false
   20    tag "check": "This applies to domain controllers. It is NA for other systems.
   21  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73361.rb:
   15    tag "stig_id": 'WN16-DC-000030'
   16    tag "fix_id": 'F-79803r1_fix'
   17:   tag "cci": ['CCI-001941', 'CCI-001942']
   18:   tag "nist": ['IA-2 (8)', 'Rev_4']
   19:   tag "nist": ['IA-2 (9)', 'Rev_4']
   20:   tag "documentable": false
   21    tag "check": "This applies to domain controllers. It is NA for other systems.
   22  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73363.rb:
   19    tag "stig_id": 'WN16-DC-000040'
   20    tag "fix_id": 'F-79805r1_fix'
   21:   tag "cci": ['CCI-001941', 'CCI-001942']
   22:   tag "nist": ['IA-2 (8)', 'Rev_4']
   23:   tag "nist": ['IA-2 (9)', 'Rev_4']
   24:   tag "documentable": false
   25    tag "check": "This applies to domain controllers. It is NA for other systems.
   26  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73365.rb:
   13    tag "stig_id": 'WN16-DC-000050'
   14    tag "fix_id": 'F-79807r1_fix'
   15:   tag "cci": ['CCI-001941', 'CCI-001942']
   16:   tag "nist": ['IA-2 (8)', 'Rev_4']
   17:   tag "nist": ['IA-2 (9)', 'Rev_4']
   18:   tag "documentable": false
   19    tag "check": "This applies to domain controllers. It is NA for other systems.
   20  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73367.rb:
   16    tag "stig_id": 'WN16-DC-000060'
   17    tag "fix_id": 'F-79809r1_fix'
   18:   tag "cci": ['CCI-001941', 'CCI-001942']
   19:   tag "nist": ['IA-2 (8)', 'Rev_4']
   20:   tag "nist": ['IA-2 (9)', 'Rev_4']
   21:   tag "documentable": false
   22    tag "check": "This applies to domain controllers. It is NA for other systems.
   23  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73389.rb:
   27    tag "stig_id": 'WN16-DC-000170'
   28    tag "fix_id": 'F-86715r2_fix'
   29:   tag "cci": ['CCI-000172', 'CCI-002234']
   30:   tag "nist": ['AU-12 c', 'Rev_4']
   31:   tag "nist": ['AC-6 (9)', 'Rev_4']
   32:   tag "documentable": false
   33    tag "check": "This applies to domain controllers. It is NA for other systems.
   34  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73391.rb:
   27    tag "stig_id": 'WN16-DC-000180'
   28    tag "fix_id": 'F-79833r1_fix'
   29:   tag "cci": ['CCI-000172', 'CCI-002234']
   30:   tag "nist": ['AU-12 c', 'Rev_4']
   31:   tag "nist": ['AC-6 (9)', 'Rev_4']
   32:   tag "documentable": false
   33    tag "check": "This applies to domain controllers. It is NA for other systems.
   34  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73393.rb:
   27    tag "stig_id": 'WN16-DC-000190'
   28    tag "fix_id": 'F-79835r1_fix'
   29:   tag "cci": ['CCI-000172', 'CCI-002234']
   30:   tag "nist": ['AU-12 c', 'Rev_4']
   31:   tag "nist": ['AC-6 (9)', 'Rev_4']
   32:   tag "documentable": false
   33    tag "check": "This applies to domain controllers. It is NA for other systems.
   34  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73395.rb:
   28    tag "stig_id": 'WN16-DC-000200'
   29    tag "fix_id": 'F-79837r1_fix'
   30:   tag "cci": ['CCI-000172', 'CCI-002234']
   31:   tag "nist": ['AU-12 c', 'Rev_4']
   32:   tag "nist": ['AC-6 (9)', 'Rev_4']
   33:   tag "documentable": false
   34    tag "check": "This applies to domain controllers. It is NA for other systems.
   35  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73397.rb:
   27    tag "stig_id": 'WN16-DC-000210'
   28    tag "fix_id": 'F-79839r1_fix'
   29:   tag "cci": ['CCI-000172', 'CCI-002234'] 
   30:   tag "nist": ['AU-12 c', 'Rev_4']
   31:   tag "nist": ['AC-6 (9)', 'Rev_4']
   32:   tag "documentable": false
   33    tag "check": "This applies to domain controllers. It is NA for other systems.
   34  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73399.rb:
   27    tag "stig_id": 'WN16-DC-000220'
   28    tag "fix_id": 'F-79841r1_fix'
   29:   tag "cci": ['CCI-000172', 'CCI-002234']
   30:   tag "nist": ['AU-12 c', 'Rev_4']
   31:   tag "nist": ['AC-6 (9)', 'Rev_4']
   32:   tag "documentable": false
   33    tag "check": "This applies to domain controllers. It is NA for other systems.
   34  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73417.rb:
   22    tag "fix_id": 'F-79859r1_fix'
   23    tag "cci": ['CCI-000018', 'CCI-000172', 'CCI-001403', 'CCI-001404',
   24:               'CCI-001405', 'CCI-002130']
   25:   tag "nist": ['AC-2 (4)', 'Rev_4']
   26:   tag "nist": ['AU-12 c', 'Rev_4']
   27:   tag "documentable": false
   28    tag "check": "This applies to domain controllers. It is NA for other systems.
   29  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73419.rb:
   20    tag "stig_id": 'WN16-AU-000100'
   21    tag "fix_id": 'F-79861r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "Security Option Audit: Force audit policy subcategory
   27    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73423.rb:
   22    tag "fix_id": 'F-79865r1_fix'
   23    tag "cci": ['CCI-000018', 'CCI-000172', 'CCI-001403', 'CCI-001404',
   24:               'CCI-001405', 'CCI-002130']
   25:   tag "nist": ['AC-2 (4)', 'Rev_4']
   26:   tag "nist": ['AU-12 c', 'Rev_4']
   27:   tag "documentable": false
   28    tag "check": "Security Option Audit: Force audit policy subcategory
   29    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73427.rb:
   22    tag "fix_id": 'F-79869r1_fix'
   23    tag "cci": ['CCI-000018', 'CCI-000172', 'CCI-001403', 'CCI-001404',
   24:               'CCI-001405', 'CCI-002130']
   25:   tag "nist": ['AC-2 (4)', 'Rev_4']
   26:   tag "nist": ['AU-12 c', 'Rev_4']
   27:   tag "documentable": false
   28    tag "check": "Security Option Audit: Force audit policy subcategory
   29    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73429.rb:
   22    tag "fix_id": 'F-79871r1_fix'
   23    tag "cci": ['CCI-000018', 'CCI-000172', 'CCI-001403', 'CCI-001404',
   24:               'CCI-001405', 'CCI-002130']
   25:   tag "nist": ['AC-2 (4)', 'Rev_4']
   26:   tag "nist": ['AU-12 c', 'Rev_4']
   27:   tag "documentable": false
   28    tag "check": "Security Option Audit: Force audit policy subcategory
   29    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73433.rb:
   19    tag "stig_id": 'WN16-AU-000170'
   20    tag "fix_id": 'F-79875r1_fix'
   21:   tag "cci": ['CCI-000172', 'CCI-002234']
   22:   tag "nist": ['AU-12 c', 'Rev_4']
   23:   tag "nist": ['AC-6 (9)', 'Rev_4']
   24:   tag "documentable": false
   25    tag "check": "Security Option Audit: Force audit policy subcategory
   26    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73437.rb:
   21    tag "stig_id": 'WN16-DC-000250'
   22    tag "fix_id": 'F-79879r1_fix'
   23:   tag "cci": ['CCI-000172', 'CCI-002234']
   24:   tag "nist": ['AU-12 c', 'Rev_4']
   25:   tag "nist": ['AC-6 (9)', 'Rev_4']
   26:   tag "documentable": false
   27    tag "check": "This applies to domain controllers. It is NA for other systems.
   28  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73439.rb:
   20    tag "stig_id": 'WN16-DC-000260'
   21    tag "fix_id": 'F-79881r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "This applies to domain controllers. It is NA for other systems.
   27  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73441.rb:
   20    tag "stig_id": 'WN16-DC-000270'
   21    tag "fix_id": 'F-79883r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "This applies to domain controllers. It is NA for other systems.
   27  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73443.rb:
   19    tag "stig_id": 'WN16-AU-000220'
   20    tag "fix_id": 'F-79885r1_fix'
   21:   tag "cci": ['CCI-000172', 'CCI-001404']
   22:   tag "nist": ['AU-12 c', 'Rev_4']
   23:   tag "nist": ['AC-2 (4)', 'Rev_4']
   24:   tag "documentable": false
   25    tag "check": "Security Option Audit: Force audit policy subcategory
   26    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73445.rb:
   19    tag "stig_id": 'WN16-AU-000230'
   20    tag "fix_id": 'F-79887r1_fix'
   21:   tag "cci": ['CCI-000172', 'CCI-001404']
   22:   tag "nist": ['AU-12 c', 'Rev_4']
   23:   tag "nist": ['AC-2 (4)', 'Rev_4']
   24:   tag "documentable": false
   25    tag "check": "Security Option Audit: Force audit policy subcategory
   26    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73449.rb:
   22    tag "stig_id": 'WN16-AU-000250'
   23    tag "fix_id": 'F-79891r1_fix'
   24:   tag "cci": ['CCI-000067', 'CCI-000172']
   25:   tag "nist": ['AC-17 (1)', 'Rev_4']
   26:   tag "nist": ['AU-12 c', 'Rev_4']
   27:   tag "documentable": false
   28    tag "check": "Security Option Audit: Force audit policy subcategory
   29    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73451.rb:
   22    tag "stig_id": 'WN16-AU-000260'
   23    tag "fix_id": 'F-79893r1_fix'
   24:   tag "cci": ['CCI-000067', 'CCI-000172']
   25:   tag "nist": ['AC-17 (1)', 'Rev_4']
   26:   tag "nist": ['AU-12 c', 'Rev_4']
   27:   tag "documentable": false
   28    tag "check": "Security Option Audit: Force audit policy subcategory
   29    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73453.rb:
   22    tag "stig_id": 'WN16-AU-000270'
   23    tag "fix_id": 'F-79895r1_fix'
   24:   tag "cci": ['CCI-000067', 'CCI-000172']
   25:   tag "nist": ['AC-17 (1)', 'Rev_4']
   26:   tag "nist": ['AU-12 c', 'Rev_4']
   27:   tag "documentable": false
   28    tag "check": "Security Option Audit: Force audit policy subcategory
   29    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73461.rb:
   19    tag "stig_id": 'WN16-AU-000310'
   20    tag "fix_id": 'F-79903r1_fix'
   21:   tag "cci": ['CCI-000172', 'CCI-002234']
   22:   tag "nist": ['AU-12 c', 'Rev_4']
   23:   tag "nist": ['AC-6 (9)', 'Rev_4']
   24:   tag "documentable": false
   25    tag "check": "Security Option Audit: Force audit policy subcategory
   26    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73463.rb:
   19    tag "stig_id": 'WN16-AU-000320'
   20    tag "fix_id": 'F-79905r1_fix'
   21:   tag "cci": ['CCI-000172', 'CCI-002234']
   22:   tag "nist": ['AU-12 c', 'Rev_4']
   23:   tag "nist": ['AC-6 (9)', 'Rev_4']
   24:   tag "documentable": false
   25    tag "check": "Security Option Audit: Force audit policy subcategory
   26    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73465.rb:
   20    tag "stig_id": 'WN16-AU-000330'
   21    tag "fix_id": 'F-79907r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "Security Option Audit: Force audit policy subcategory
   27    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73467.rb:
   20    tag "stig_id": 'WN16-AU-000340'
   21    tag "fix_id": 'F-79909r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "Security Option Audit: Force audit policy subcategory
   27    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73469.rb:
   21    tag "stig_id": 'WN16-AU-000350'
   22    tag "fix_id": 'F-79911r1_fix'
   23:   tag "cci": ['CCI-000172', 'CCI-002234']
   24:   tag "nist": ['AU-12 c', 'Rev_4']
   25:   tag "nist": ['AC-6 (9)', 'Rev_4']
   26:   tag "documentable": false
   27    tag "check": "Security Option Audit: Force audit policy subcategory
   28    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73471.rb:
   21    tag "stig_id": 'WN16-AU-000360'
   22    tag "fix_id": 'F-79913r1_fix'
   23:   tag "cci": ['CCI-000172', 'CCI-002234']
   24:   tag "nist": ['AU-12 c', 'Rev_4']
   25:   tag "nist": ['AC-6 (9)', 'Rev_4']
   26:   tag "documentable": false
   27    tag "check": "Security Option Audit: Force audit policy subcategory
   28    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73473.rb:
   20    tag "stig_id": 'WN16-AU-000370'
   21    tag "fix_id": 'F-79915r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "Security Option Audit: Force audit policy subcategory
   27    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73475.rb:
   20    tag "stig_id": 'WN16-AU-000380'
   21    tag "fix_id": 'F-79917r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "Security Option Audit: Force audit policy subcategory
   27    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73477.rb:
   20    tag "stig_id": 'WN16-AU-000390'
   21    tag "fix_id": 'F-79919r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "Security Option Audit: Force audit policy subcategory
   27    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73479.rb:
   20    tag "stig_id": 'WN16-AU-000400'
   21    tag "fix_id": 'F-79921r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "Security Option Audit: Force audit policy subcategory
   27    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73481.rb:
   20    tag "stig_id": 'WN16-AU-000410'
   21    tag "fix_id": 'F-79923r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "Security Option Audit: Force audit policy subcategory
   27    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73483.rb:
   20    tag "stig_id": 'WN16-AU-000420'
   21    tag "fix_id": 'F-79925r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "Security Option Audit: Force audit policy subcategory
   27    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73489.rb:
   20    tag "stig_id": 'WN16-AU-000440'
   21    tag "fix_id": 'F-79931r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "Security Option Audit: Force audit policy subcategory
   27    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73491.rb:
   20    tag "stig_id": 'WN16-AU-000450'
   21    tag "fix_id": 'F-79933r1_fix'
   22:   tag "cci": ['CCI-000172', 'CCI-002234']
   23:   tag "nist": ['AU-12 c', 'Rev_4']
   24:   tag "nist": ['AC-6 (9)', 'Rev_4']
   25:   tag "documentable": false
   26    tag "check": "Security Option Audit: Force audit policy subcategory
   27    settings (Windows Vista or later) to override audit policy category settings

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73605.rb:
   14    tag "stig_id": 'WN16-PK-000010'
   15    tag "fix_id": 'F-87311r1_fix'
   16:   tag "cci": ['CCI-000185', 'CCI-002470']
   17:   tag "nist": ['IA-5 (2) (a)', 'Rev_4']
   18:   tag "nist": ['SC-23 (5)', 'Rev_4']
   19:   tag "documentable": false
   20    tag "check": "The certificates and thumbprints referenced below apply to
   21    unclassified systems; see PKE documentation for other networks.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73607.rb:
   14    tag "stig_id": 'WN16-PK-000020'
   15    tag "fix_id": 'F-87313r2_fix'
   16:   tag "cci": ['CCI-000185', 'CCI-002470']
   17:   tag "nist": ['IA-5 (2) (a)', 'Rev_4']
   18:   tag "nist": ['SC-23 (5)', 'Rev_4']
   19:   tag "documentable": false
   20    tag "check": "This is applicable to unclassified systems. It is NA for others.
   21  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73609.rb:
   15    tag "stig_id": 'WN16-PK-000030'
   16    tag "fix_id": 'F-87315r1_fix'
   17:   tag "cci": ['CCI-000185', 'CCI-002470']
   18:   tag "nist": ['IA-5 (2) (a)', 'Rev_4']
   19:   tag "nist": ['SC-23 (5)', 'Rev_4']
   20:   tag "documentable": false
   21    tag "check": "This is applicable to unclassified systems. It is NA for others.
   22  

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73617.rb:
   18    tag "fix_id": 'F-80067r1_fix'
   19    tag "cci": ['CCI-000765', 'CCI-000766', 'CCI-000767', 'CCI-000768',
   20:               'CCI-001948']
   21:   tag "nist": ['IA-2 (1)', 'Rev_4']
   22:   tag "nist": ['IA-2 (2)', 'Rev_4']
   23:   tag "nist": ['IA-2 (3)', 'Rev_4']
   24:   tag "nist": ['IA-2 (4)', 'Rev_4']
   25:   tag "nist": ['IA-2 (11)', 'Rev_4']
   26    tag "documentable": false
   27    tag "check": "This applies to domain controllers. It is NA for other systems.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73633.rb:
   14    tag "stig_id": 'WN16-SO-000080'
   15    tag "fix_id": 'F-80083r1_fix'
   16:   tag "cci": ['CCI-002418', 'CCI-002421']
   17:   tag "nist": ['SC-8', 'Rev_4']
   18:   tag "nist": ['SC-8 (1)', 'Rev_4']
   19:   tag "documentable": false
   20    tag "check": "If the following registry value does not exist or is not
   21    configured as specified, this is a finding.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73635.rb:
   14    tag "stig_id": 'WN16-SO-000090'
   15    tag "fix_id": 'F-80085r1_fix'
   16:   tag "cci": ['CCI-002418', 'CCI-002421']
   17:   tag "nist": ['SC-8', 'Rev_4']
   18:   tag "nist": ['SC-8 (1)', 'Rev_4']
   19:   tag "documentable": false
   20    tag "check": "If the following registry value does not exist or is not
   21    configured as specified, this is a finding.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73637.rb:
   14    tag "stig_id": 'WN16-SO-000100'
   15    tag "fix_id": 'F-80087r1_fix'
   16:   tag "cci": ['CCI-002418', 'CCI-002421']
   17:   tag "nist": ['SC-8', 'Rev_4']
   18:   tag "nist": ['SC-8 (1)', 'Rev_4']
   19:   tag "documentable": false
   20    tag "check": "If the following registry value does not exist or is not
   21    configured as specified, this is a finding.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73643.rb:
   15    tag "stig_id": 'WN16-SO-000130'
   16    tag "fix_id": 'F-80093r1_fix'
   17:   tag "cci": ['CCI-002418', 'CCI-002421']
   18:   tag "nist": ['SC-8', 'Rev_4']
   19:   tag "nist": ['SC-8 (1)', 'Rev_4']
   20:   tag "documentable": false
   21    tag "check": "If the following registry value does not exist or is not
   22    configured as specified, this is a finding.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73647.rb:
   15    tag "fix_id": 'F-80097r2_fix'
   16    tag "cci": ['CCI-000048', 'CCI-000050', 'CCI-001384', 'CCI-001385',
   17:               'CCI-001386', 'CCI-001387', 'CCI-001388']
   18:   tag "nist": ['AC-8 a', 'Rev_4']
   19:   tag "nist": ['AC-8 b', 'Rev_4']
   20:   tag "nist": ['AC-8 c 1', 'Rev_4']
   21:   tag "nist": ['AC-8 c 2', 'Rev_4']
   22:   tag "nist": ['AC-8 c 3', 'Rev_4']
   23    tag "documentable": false
   24    tag "check": "If the following registry value does not exist or is not

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73649.rb:
   13    tag "fix_id": 'F-80099r1_fix'
   14    tag "cci": ['CCI-000048', 'CCI-001384', 'CCI-001385', 'CCI-001386',
   15:               'CCI-001387', 'CCI-001388']
   16:   tag "nist": ['AC-8 a', 'Rev_4']
   17:   tag "nist": ['AC-8 b', 'Rev_4']
   18:   tag "nist": ['AC-8 c 1', 'Rev_4']
   19:   tag "nist": ['AC-8 c 2', 'Rev_4']
   20:   tag "nist": ['AC-8 c 3', 'Rev_4']
   21    tag "documentable": false
   22    tag "check": "If the following registry value does not exist or is not

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73653.rb:
   14    tag "stig_id": 'WN16-SO-000190'
   15    tag "fix_id": 'F-80103r1_fix'
   16:   tag "cci": ['CCI-002418', 'CCI-002421']
   17:   tag "nist": ['SC-8', 'Rev_4']
   18:   tag "nist": ['SC-8 (1)', 'Rev_4']
   19:   tag "documentable": false
   20    tag "check": "If the following registry value does not exist or is not
   21    configured as specified, this is a finding.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73655.rb:
   14    tag "stig_id": 'WN16-SO-000200'
   15    tag "fix_id": 'F-80105r1_fix'
   16:   tag "cci": ['CCI-002418', 'CCI-002421']
   17:   tag "nist": ['SC-8', 'Rev_4']
   18:   tag "nist": ['SC-8 (1)', 'Rev_4']
   19:   tag "documentable": false
   20    tag "check": "If the following registry value does not exist or is not
   21    configured as specified, this is a finding.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73659.rb:
   15    tag "stig_id": 'WN16-SO-000220'
   16    tag "fix_id": 'F-80109r1_fix'
   17:   tag "cci": ['CCI-001133', 'CCI-002361']
   18:   tag "nist": ['SC-10', 'Rev_4']
   19:   tag "nist": ['AC-12', 'Rev_4']
   20:   tag "documentable": false
   21    tag "check": "If the following registry value does not exist or is not
   22    configured as specified, this is a finding.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73661.rb:
   14    tag "stig_id": 'WN16-SO-000230'
   15    tag "fix_id": 'F-80111r1_fix'
   16:   tag "cci": ['CCI-002418', 'CCI-002421']
   17:   tag "nist": ['SC-8', 'Rev_4']
   18:   tag "nist": ['SC-8 (1)', 'Rev_4']
   19:   tag "documentable": false
   20    tag "check": "If the following registry value does not exist or is not
   21    configured as specified, this is a finding.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73663.rb:
   14    tag "stig_id": 'WN16-SO-000240'
   15    tag "fix_id": 'F-80113r1_fix'
   16:   tag "cci": ['CCI-002418', 'CCI-002421']
   17:   tag "nist": ['SC-8', 'Rev_4']
   18:   tag "nist": ['SC-8 (1)', 'Rev_4']
   19:   tag "documentable": false
   20    tag "check": "If the following registry value does not exist or is not
   21    configured as specified, this is a finding.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73701.rb:
   14    tag "stig_id": 'WN16-SO-000430'
   15    tag "fix_id": 'F-80151r1_fix'
   16:   tag "cci": ['CCI-000068', 'CCI-002450']
   17:   tag "nist": ['AC-17 (2)', 'Rev_4']
   18:   tag "nist": ['SC-13', 'Rev_4']
   19:   tag "documentable": false
   20    tag "check": "If the following registry value does not exist or is not
   21    configured as specified, this is a finding.

stig-microsoft-windows-server-2016-v1r4-baseline/controls/V-73793.rb:
   19    tag "fix_id": 'F-80243r1_fix'
   20    tag "cci": ['CCI-000162', 'CCI-000163', 'CCI-000164', 'CCI-000171',
   21:               'CCI-001914']
   22:   tag "nist": ['AU-9', 'Rev_4']
   23:   tag "nist": ['AU-9 (1)', 'Rev_4']
   24:   tag "nist": ['AU-12 b', 'Rev_4']
   25:   tag "nist": ['AU-12 (3)', 'Rev_4']
   26:   tag "documentable": false
   27    tag "check": "Verify the effective setting in Local Group Policy Editor.
   28  

63 matches across 59 files

```

### LINKED ISSUE #17: V-73393 adjust for inspec subject block limitation
Inspec has a limitation where subject {} blocks does not function properly within a describe.one block

Same applies to an input() or attribute() block within a describe.one block

https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/42fbf823bfe09d727a12476deda3762fe266e3f3/controls/V-73393.rb#L119-L130

Current design of the test results in powershell resource being unrecognized.
```
Message: undefined method `powershell' for #<RSpec::ExampleGroups::TheFilePermissionsOnADCNInfrastructureDCVsphereadDCNet:0x00007ff42e8cf0a8>
```

Please update the test to call the powershell call outside the describe.one block and place it in a variable.

The variable can be using within the subject{} block within the describe.one block

### LINKED ISSUE #18: V-73607  Certificate expiration not checked
V-73607 current test code does not validated the expiration date of the DOD Certificate

### LINKED ISSUE #19: V-73611: Current test code error prone
V-73611: Current test code error prone because it relized on comparison to a null string...

suggested test code 
```
 Get-ChildItem -Path Cert:\LocalMachine\ | ConvertTo-Json
.
.
.
    {
        "StoreHandle":  null,
        "Location":  2,
        "Name":  "My",
        "Certificates":  [

                         ],
        "PSPath":  "Microsoft.PowerShell.Security\\Certificate::My",
        "PSParentPath":  "",
        "PSChildName":  "My",
        "PSDrive":  {
                        "CurrentLocation":  "",
                        "Name":  "Cert",
                        "Provider":  "Microsoft.PowerShell.Security\\Certificate",
                        "Root":  "\\",
                        "Description":  "X509 Certificate Provider",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.CertificateProvider",
                           "HelpFile":  "Microsoft.PowerShell.Security.dll-Help.xml",
                           "Name":  "Certificate",
                           "PSSnapIn":  null,
                           "ModuleName":  "Microsoft.PowerShell.Security",
                           "Module":  "Microsoft.PowerShell.Security",
                           "Description":  "",
                           "Capabilities":  16,
                           "Home":  "",
                           "Drives":  "Cert"
                       },
        "PSIsContainer":  true
    },
.
.
.
.


```

### LINKED ISSUE #22: unable to check HKLM:\Security ACL
https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/4e835f41b8153ed1b9b1e381a5754ba75d0d2f64/controls/V-73255.rb#L109-L124

The other keys like `HKLM:\Software` and `HKLM:System` return their ACLs when executing Get-ACL

### PR DESCRIPTION
**Pull request by kkola**
I have reviewed about 249 controls and these include the 22 files that have changed in this PR. 

The list is attached [here](https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/files/3718701/Windows2016Controls-10-11-2019.xlsx).  

Fixes #6 
Fixes #7 
Fixes #8 
Fixes #9
Fixes #11 
Fixes #12 
Fixes #13  
Fixes #14 
Fixes #15
Fixes #16 
Fixes #17 
Fixes #18 
Fixes #19 
Fixes #20  
Fixes #21
Fixes #22

Aaron Lippold <lippold@gmail.com>

### CODE REVIEW

**Comment by rx294** [comment]
Please address the issue addressed in #6

**Comment by rx294** [comment]
Please address the issue addressed in #7

**Comment by rx294** [comment]
Please address the issue addressed in #9

**Comment by rx294** [comment]
Please address the issue addressed in #11

**Comment by rx294** [comment]
Please address the issue addressed in #12

**Comment by rx294** [comment]
Please address the issue addressed in #13

**Comment by kkola** [comment]
@rx294 As of 11/6/2019, 266 controls have been addressed and 9 controls are remaining since I'm unable to move forward with resolving the issues (#14  and #15). Here's the updated spreadsheet. 
[Windows2016Controls-11-6-2019.xlsx](https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/files/3815756/Windows2016Controls-11-6-2019.xlsx)

**Comment by kkola** [comment]
@rx294 the latest commits since my last comment resolve all remaining issues and should have addressed the entire control set in the profile. Please review.

> @rx294 As of 11/6/2019, 266 controls have been addressed and 9 controls are remaining since I'm unable to move forward with resolving the issues (#14 and #15). Here's the updated spreadsheet.
> [Windows2016Controls-11-6-2019.xlsx](https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/files/3815756/Windows2016Controls-11-6-2019.xlsx)

File: controls/V-73439.rb [hunk 1]
```diff
@@ -63,7 +63,7 @@
     end
   end
 
-  if !domain_role == '4' && !domain_role == '5'
+  if !(domain_role == '4') && !(domain_role == '5')
```
Comment (aaronlippold) [inline controls/V-73439.rb]: unless (domain_role == 4 || domain_role==5)
