### PR TITLE
Baseline Issues Fixes

### LINKED ISSUE #3: V-73241	The Windows Server 2016 system must use an anti-virus program.
Tests should be updated to cover Windows Defender as well.

### LINKED ISSUE #4: ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError) error
Running this on a Windows 2016 stock image and attempting to output the format in json yielded the UTF error.

This is related to https://github.com/inspec/inspec/issues/3375

I identified the following controls that cause the issue:

In controls `73607, 73609, 78127`, the `...` need's to be removed or escaped.

In control `73285` the `-` in `-AccountExpiring` needs to be escaped

```
controls/V-73285.rb:50:  Enter \"Search-ADAccount –AccountExpiring | FT Name, AccountExpirationDate\".
controls/V-73607.rb:73:  For each certificate with \"DoD Root CA…\" under \"Issued To\" and \"DoD
controls/V-73607.rb:74:  Interoperability Root CA…\" under \"Issued By\":
controls/V-73609.rb:66:  For each certificate with \"US DoD CCEB Interoperability Root CA …\" under
controls/V-78127.rb:28:(Unresolved SIDs have the format of \"*S-1-…\".)
```

After removing or escaping these, the output saves to json properly

### LINKED ISSUE #33: V-73533 - Add clause for standalone systems
This control is currently configured to check for DCs but not standalone systems. Need to add a check for if the system is on a domain or not.

This applies to member servers. For domain controllers and standalone systems, this is NA.

Something like this should work.

//Add line after 31
member_of_domain = command('(gwmi win32_computersystem).partofdomain').stdout.strip

//Add clause after 43
```
...
  if member_of_domain == 'False'
    impact 0.0
    desc 'This system is not a member of a domain, therefore this control is not applicable as it only applies to member servers'
  end
...
```

### PR DESCRIPTION
**Pull request by karikarshivani**
Details regarding the following issues are listed in those specific issues. Please review them if you'd like to access the json results and any related information.

Fixes #3 
Fixes #4 
Fixes #33 

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

### CODE REVIEW

File: controls/V-73241.rb [hunk 1]
```diff
@@ -28,5 +31,9 @@
     describe registry_key('HKLM\SOFTWARE\McAfee\Endpoint\AV\ProductVersion') do
       it { should exist }
     end
+    describe "Windows Defender" do
+      subject { windefend }
+      it { should eq "Running" }
+    end
```
Comment (karikarshivani) [inline controls/V-73241.rb:37]: This test was added in response to #3 in order to check if Windows Defender was enabled.

File: controls/V-73285.rb [hunk 2]
```diff
@@ -69,71 +69,70 @@
   Local accounts can be configured to expire with the command Net user
   [username] /expires:[mm/dd/yyyy], where username is the name of the temporary
   user account."
-  emergency_account = input('emergency_account')
-  if !emergency_account.empty?
 
-    emergency_account.each do |user|
+  domain_role = command('wmic computersystem get domainrole | Findstr /v DomainRole').stdout.strip
+  emergency_accounts_list = input('emergency_accounts')
+  emergency_accounts_data = []
```
Comment (karikarshivani) [inline controls/V-73285.rb:75]: Reviewed several controls to address #4 and standardized V-73285 using the 2019 approach

File: controls/V-73533.rb [hunk 3]
```diff
@@ -30,22 +30,14 @@
   domain-joined computers to Disabled."
   domain_role = command('wmic computersystem get domainrole | Findstr /v DomainRole').stdout.strip
 
-  if !(domain_role == '4') && !(domain_role == '5') && !(domain_role == '2')
+  if domain_role == '3'
```
Comment (karikarshivani) [inline controls/V-73533.rb:33]: Use the approach from Windows Server 2019 to address #33
